# Generated by Django 2.2.6 on 2019-10-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='mob',
            field=models.CharField(max_length=50),
        ),
    ]
